server:
  port: 8080

spring:
  application:
    name: DataForge-API
  main:
    web-application-type: reactive

bridge:
  base-url: https://api.bridgedataoutput.com/api/v2
  encrypted-token : G8kU69cRf9iz0ecVU1wrYw==:J5vtNrwdcw/mvYZMH5rR/WZyKdL3n55tBET0Aossj4A9Vhtfyk/gCo01EO7osSXJ
  mock-url: https://3eee4e18-37f2-4f16-8ab1-f72cad864cf1.mock.pstmn.io/api/v2

springdoc:
  override-with-generic-response: false

encryption:
  key: 12345678901234567890123456789012
  algorithm: AES/CBC/PKCS5Padding
  iv: 1234567890123456


