server:
  port: 8080

spring:
  application:
    name: DataForge-API
  main:
    web-application-type: reactive

bridge:
  base-url: https://api.bridgedataoutput.com/api/v2
  access-token: 0ae2d6309e1b7947430d6147fd3d8a44

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
